name: nasa_pictures
description: A simple app to browse nasa astronomy pictures from apod
publish_to: 'none'
version: 0.0.3+22080008

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: '>=0.13.0 <2.0.0'
  intl: '>=0.18.0 <0.20.0'
  fluentui_system_icons: ^1.1.177
  fade_shimmer: ^2.0.1
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.2
  quiver: ^3.1.0
  equatable: ^2.0.3
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  logging: ^1.0.2
  logging_manager: ^2.3.1
  logging_manager_flutter: ^2.2.1
  cached_network_image: ^3.2.1
  shared_preferences: ^2.0.15
  drift: ^2.0.2+1
  path: ^1.8.2
  path_provider: ^2.0.11
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  flutter_gen_runner: ^5.4.0
  freezed: ^2.1.0+1
  mocktail_image_network: ^1.1.0
  drift_dev: ^2.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/data/
    - assets/icons/
    - assets/brand/
